### ISSUE TITLE
Chapter 6.1 numbers

### ISSUE THREAD

**Issue by mediafinger** [rubymonsters/ruby-for-beginners#11]
The information given in this file:
https://github.com/rubymonsters/ruby-for-beginners/blob/master/source/06-built_in_classes/01-numbers.md

is just wrong. It is not correct that the result of a calculation with a Float and an Integer will always return the type of the first one.

Please play around with irb and fix this information (or if it actually should work like this in the Ruby version you use, than please document which Ruby version that is and point out that other versions will yield different results).

**Comment by mediafinger** [comment]
Ah, another thing: great guide! I really recommend my beginners http://www.meetup.com/Web-Development-with-Ruby-on-Rails-for-Beginners-Barcelona/ to read it :-)

**Comment by svenfuchs** [comment]
Sorry, @mediafinger. Only saw this just now.

You're so right. Should be fixed: http://ruby-for-beginners.rubymonstas.org/built_in_classes/numbers.html
