### ISSUE TITLE
Broken navigation links due to relative URLs

### ISSUE THREAD

**Issue by mitio** [rubymonsters/ruby-for-beginners#2]
When a page from a subsection in the left menu is opened, all navigation links break down. This is due to the fact that all links in the nav are relative and the subsection pages are in a folder.

For example, visit this page and try any of the nav links:
<http://ruby-for-beginners.rubymonstas.org/03-learning_to_program/04-learning_modes.html>

Moreover, it seems the code in the GH pages is not being built from the sources which are in the master branch. When I clone the repo and build it locally, the left navigation tree is flat and this problem does not occur. That's why I was not able to offer a fix.

**Comment by mitio** [comment]
This is now fixed in master, probably in 5c7d8945e6c061d0f31b0f00853d5041740b96b3.

**Comment by svenfuchs** [comment]
Thanks for looking into it, @mitio. I indeed forgot to push my last commit to GitHub, too.
