### ISSUE TITLE
There is no 1,234.56 number format in Ruby

### ISSUE THREAD

**Issue by svenfuchs** [rubymonsters/ruby-for-beginners#21]
http://ruby-for-beginners.rubymonstas.org/built_in_classes/numbers.html is just wrong

**Comment by fidothe** [comment]
yeah, you can write `1_234.56` though

**Comment by svenfuchs** [comment]
Fixed with https://github.com/rubymonsters/ruby-for-beginners/commit/56f7b1dc302f86008053b8b90a80d5b8fa6dc178
