### ISSUE TITLE
Wrong links

### ISSUE THREAD

**Issue by musagetin** [rubymonsters/ruby-for-beginners#5]
There are same mistakes in the links to exercises: http://ruby-for-beginners.rubymonstas.org/16-exercises/... instead of http://ruby-for-beginners.rubymonstas.org/17-exercises/... (starting with http://ruby-for-beginners.rubymonstas.org/06-built_in_classes/01-numbers.html and so on)

**Comment by svenfuchs** [comment]
Thanks for the issue, @musagetin. Should be fixed.
