### ISSUE TITLE
Exercise 3.3

### ISSUE THREAD

**Issue by musagetin** [rubymonsters/ruby-for-beginners#6]
http://ruby-for-beginners.rubymonstas.org/17-exercises/03-arrays_1.html
Mistake in solution:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
numbers.select { |number| number.even? } #method select returns a new array, but "old" array numbers doesn't change
p numbers # [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

I propose this solution:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
numbers = numbers.select { |number| number.even? }
p numbers # [2, 4, 6, 8, 10]

**Comment by sabrina-ulbrich** [comment]
You're right, thank you @musagetin  :+1:

**Comment by svenfuchs** [comment]
You rock, @musagetin
